logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

server:
  port: 8081

logging:
  level:
    victor.training: DEBUG

management.endpoints.web.exposure.include: "*"

